#████████╗██╗███╗░░░███╗░█████╗░░█████╗░███╗░░██╗████████╗██╗░██████╗██████╗░░█████╗░███╗░░░███╗
#╚══██╔══╝██║████╗░████║██╔══██╗██╔══██╗████╗░██║╚══██╔══╝██║██╔════╝██╔══██╗██╔══██╗████╗░████║
#░░░██║░░░██║██╔████╔██║███████║███████║██╔██╗██║░░░██║░░░██║╚█████╗░██████╔╝███████║██╔████╔██║
#░░░██║░░░██║██║╚██╔╝██║██╔══██║██╔══██║██║╚████║░░░██║░░░██║░╚═══██╗██╔═══╝░██╔══██║██║╚██╔╝██║
#░░░██║░░░██║██║░╚═╝░██║██║░░██║██║░░██║██║░╚███║░░░██║░░░██║██████╔╝██║░░░░░██║░░██║██║░╚═╝░██║
#░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝░░░╚═╝░░░╚═╝╚═════╝░╚═╝░░░░░╚═╝░░╚═╝╚═╝░░░░░╚═╝
#
#plugin by Timur Rootkovskiy (Adminov)
#vk - @timurroot
#
SPAM_MESSAGE: "&c Подожди! Ты отправляешь сообщения слишком быстро!"
#
#enter the value in seconds, enter ONLY NUMBERS here, otherwise the plugin will not work!!
COOLDOWN: 1
#
#thanks for use my plugin <3